services:
  ros-dev-windows:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        ROS_DISTRO: humble
    image: ds-crazyflies:dev
    container_name: ds-crazyflies-dev
    network_mode: host
    ipc: host
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=30
      - ROS_AUTOMATIC_DISCOVERY_RANGE=SUBNET
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - QT_X11_NO_MITSHM=1
    volumes:
      - ../src:/ds/ds-crazyflies/src:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /run/udev:/run/udev:ro
      - /dev:/dev
    device_cgroup_rules:
      - "c 189:* rmw"
    working_dir: /ds/ds-crazyflies
    command: bash
    privileged: true
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all 
              capabilities: [gpu]